<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.0.2</Version>
    <AssemblyName>AutoMakeTimeline</AssemblyName>
    <RootNamespace>AutoMakeTimeline</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="../assets/icon.png" Link="images/icon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
